---
title: "HR Analysis"
output: 
  html_document:
    keep_md: true
---

```{r package, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load required packages
library(tidyverse)
library(dplyr)
library(ggplot2)
library(Hmisc)
library(knitr)
library(kableExtra)
library(scales)
```

## Data PreProcessing

### Basic Setup

```{r setup, include=TRUE}
#read data
test <- read.csv("aug_test.csv", stringsAsFactors = F)
train <- read.csv("aug_train.csv", stringsAsFactors = F)

colnames(test)
colnames(train)

summary_test <- describe(test)
summary_test

summary_train <- describe(train)
summary_train

length(unique(test[,"enrollee_id"])) # no duplicates
length(unique(train[,"enrollee_id"])) # no duplicates

sapply(test, function(x) sum(is.na(x) | x == 0 | x == ""))
sapply(train, function(x) sum(is.na(x) | x == 0 | x == ""))

#test1 <- test1[!(test1$Customer_Age %in% boxplot(df$Customer_Age)$out),]

```

### Visualization 

#### Gender
```{r gender, include=TRUE}
# pie chart for gender
sex <- train %>%
  filter(!(gender == "")) %>% # remove blank values from 'gender'
  group_by(gender) %>%
  summarise(percent = n()/nrow(.) * 100)

pie <- ggplot(sex, aes(x = "", y = percent, fill = reorder(gender,percent))) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  geom_text(aes(x = 1.58, label = paste0(round(percent,1),"%")),
            position = position_stack(vjust = .5), size = 2.3) +
  coord_polar("y", start = 0) +
  labs(fill = "Gender") +
  guides(fill = guide_legend(reverse = TRUE)) # reverse order of legend
pie
```
여자보다 남자 비율이 월등히 높음.
실제를 반영한 것일 수도 있지만 그냥 데이터가 imbalanced한 것일 수도 있음을
생각해야함

#### Major
```{r major, include=TRUE}
# pie chart for major discipline
major <- train %>%
  filter(!(major_discipline == "")) %>% # remove blank values from 'major_discipline'
  group_by(major_discipline) %>%
  summarise(percent = n()/nrow(.) * 100)

pie <- ggplot(major, aes(x = "", y = percent, fill = reorder(major_discipline, percent))) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  geom_text(aes(x = 1.58, label = paste0(round(percent,1),"%")),
            position = position_stack(vjust = .5), size = 1.85) +
  coord_polar("y", start = 0) +
  labs(fill = "Major Discipline") +
  guides(fill = guide_legend(reverse = TRUE)) # reverse order of legend
pie
```

#### Education Level 
```{r edu, include=T}
# pie chart for education level
education <- train %>%
  filter(!(education_level == "")) %>% # remove blank values from 'major_discipline'
  group_by(education_level) %>%
  summarise(percent = n()/nrow(.) * 100)

pie <- ggplot(education, aes(x = "", y = percent, fill = reorder(education_level,percent))) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  geom_text(aes(x = 1.6, label = paste0(round(percent,1),"%")),
            position = position_stack(vjust = .5), size = 2.3) +
  coord_polar("y", start = 0) +
  labs(fill = "Education Level") +
  guides(fill = guide_legend(reverse = TRUE)) # reverse order of legend
pie

#pie <- ggplot(major, aes(x = "", y = percent, fill = major_discipline)) +
#  geom_bar(width = 1, stat = "identity", color = "white") +
#  scale_y_continuous(breaks = round(cumsum(rev(major$percent)), 1)) +
#  geom_text(aes(label = paste(round(percent,1),"%")),position = position_stack(vjust = .5)) +
#  coord_polar("y", start = 0)
#pie
```

#### Experience
```{r exp, include=T}
#my_order <- c('<1','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15',
#           '16','17','18','19','20','>20')

#exp <- train %>%
#  filter(!(experience == "")) %>%
#  #mutate(experience = ifelse(experience == "<1", "0",experience)) %>%
#  #mutate(experience = as.numeric(experience)) %>%
#  group_by(experience) %>%
#  summarise(count = n()) %>%
#  arrange(match(experience, my_order))

exp <- train %>%
  filter(!(experience == "")) %>%
  filter(!experience == ">20") %>% # remove >20 experience
  #filter(!experience == "<1") %>% # remove <1 experience
  mutate(experience = ifelse(experience == "<1", "0",experience)) %>% # treat <1 experience as 0 experience
  mutate(experience = as.numeric(experience)) %>%
  group_by(experience) %>%
  summarise(count = n())

bar <- ggplot(exp, aes(x = experience, y = count)) +
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = count), vjust = -0.3)
bar
```

#### Company Size
```{r size, include=T}
#my_order <- c('<10','10/49','50-99','100-500','500-999','1000-4999','5000-9999','10000+')

#size <- train %>%
#  filter(!(company_size == "")) %>%
#  group_by(company_size) %>%
#  summarise(count = n()) %>%
#  arrange(match(company_size, my_order))

#bar <- ggplot(size, aes(x = company_size, y = count)) +
#  geom_bar(fill = "#0073C2FF", stat = "identity") +
#  geom_text(aes(label = count), vjust = -0.3)
#bar

#-------
#not looking for job change (target=0)
size <- train %>%
  filter(target == "0") %>%
  filter(!company_size == "") %>%
  group_by(company_size) %>%
  summarise(percent = n()/nrow(.) * 100)

pie <- ggplot(size, aes(x = "", y = percent, fill = reorder(company_size,percent))) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  geom_text(aes(x = 1.6, label = paste0(round(percent,1),"%")),
            position = position_stack(vjust = .5), size = 2.3) +
  coord_polar("y", start = 0) +
  labs(fill = "Company Sizel") +
  guides(fill = guide_legend(reverse = TRUE)) # reverse order of legend
pie

# looking for job change (target=1)
size <- train %>%
  filter(target == "1") %>%
  filter(!company_size == "") %>%
  group_by(company_size) %>%
  summarise(percent = n()/nrow(.) * 100)

pie <- ggplot(size, aes(x = "", y = percent, fill = reorder(company_size,percent))) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  geom_text(aes(x = 1.6, label = paste0(round(percent,1),"%")),
            position = position_stack(vjust = .5), size = 2.3) +
  coord_polar("y", start = 0) +
  labs(fill = "Company Sizel") +
  guides(fill = guide_legend(reverse = TRUE)) # reverse order of legend
pie
```


#### Company Type
```{r company, include=T}
#total number
company <- train %>%
  filter(!company_type == "") %>%
  group_by(company_type) %>%
  summarise(count = n())

freq <- ggplot(company, aes(fct_rev(fct_reorder(company_type, count)),count)) +
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = count), vjust = -0.3) +
  labs(x = "Company Type")
freq

#not looking for job change (target=0)
nochange <- train %>%
  filter(target == "0") %>%
  filter(!company_type == "") %>%
  group_by(company_type) %>%
  summarise(count = n(), percent = n()/nrow(.) * 100)

freq <- ggplot(nochange, aes(fct_rev(fct_reorder(company_type, count)),count)) +
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = paste0(count," (", paste0(round(percent,1),"%"),")"), vjust = -0.3)) +
  labs(x = "Company Type", title = "Not Looking for Job Change")
freq

#looking for job change (target=1)
change <- train %>%
  filter(target == "1") %>%
  filter(!company_type == "") %>%
  group_by(company_type) %>%
  summarise(count = n(), percent = n()/nrow(.) * 100)

freq <- ggplot(change, aes(fct_rev(fct_reorder(company_type, count)),count)) +
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = paste0(count," (", paste0(round(percent,1),"%"),")"), vjust = -0.3)) +
  labs(x = "Company Type", title = "Looking for Job Change")
freq
```


```{r klnl}
density <- train %>%
  filter(!company_type == "") %>%
  filter(!training_hours == "")

plot <- ggplot(density, aes(x = training_hours)) +
  geom_density(aes(color = company_type))
plot

#-------
density <- train %>%
  filter(!company_type == "") %>%
  filter(!training_hours == "") %>%
  mutate(target = ifelse(target == "0", "Not Looking for Job Change","Looking for Job Change"))

plot <- ggplot(density, aes(x = training_hours)) +
  geom_density(aes(color = target))
plot

#-------
#looking for/not looking for
density <- train %>%
  filter(!experience == "") %>%
  filter(!experience == ">20") %>%
  filter(!experience == "<1") %>%
  mutate(experience = as.numeric(experience)) %>%
  mutate(target = ifelse(target == "0", "Not Looking for Job Change","Looking for Job Change"))

plot <- ggplot(density, aes(x = experience)) +
  geom_density(aes(color = target))
plot
```


