---
title: "Untitled"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load required packages
library(tidyverse)
library(dplyr)
```

## Read Dataset

```{r cars, include=TRUE}
#read dataset
df <- read.csv("BankChurners.csv", stringsAsFactors = F)
```

## Including Plots

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r pressure, echo=TRUE}
names(df)
head(df, 2)
df <- df %>%
  select(-contains('Naive'))
names(df)

#나이를 나이대로 바꾸기 43 -> 40대
agelabels <- c("20-29","30-39","40-49","50-59","60-69","70-79","80+")
dfage <- df %>%
  mutate(age = cut(Customer_Age, breaks = c(20,30,40,50,60,70,80,100), right = F, labels = agelabels)) %>%
  relocate(age, .after = Customer_Age)
dfage[1:5,]

#
nrow(df[df$Avg_Utilization_Ratio == "NA",])

#group by biography info
summary <- dfage %>%
  group_by(Gender, age, Education_Level) %>%
  summarise(mean_util_ratio = mean(Avg_Utilization_Ratio))
summary

#group by family info
summary2 <- df %>%
  group_by(Marital_Status, Dependent_count) %>%
  summarise(mean_util_ratio = mean(Avg_Utilization_Ratio))
summary2

#group by card info
summary3 <- df %>%
  group_by(Card_Category, Credit_Limit, Total_Revolving_Bal) %>%
  summarise(mean_util_ratio = mean(Avg_Utilization_Ratio))
summary3
```


